<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>20bd3c22-c82f-40ee-9fe3-601760111754</UserSecretsId>

    <!-- Suppressed Warnings (Temporary) -->
    <NoWarn>
      CS0168;  <!-- Variable declared but never used -->
      CS0169;  <!-- Field declared but never used -->
      CS0219;  <!-- Variable assigned but value never used -->
      CS0414;  <!-- Field assigned but value never used -->
      CS0649;  <!-- Field never assigned -->
      CS0162;  <!-- Unreachable code -->

      CS1998;  <!-- Async method lacks await -->

      CS1591;  <!-- Missing XML documentation -->
      CS1573;  <!-- Parameter missing XML doc -->

      CS8600;  <!-- Null conversion -->
      CS8601;
      CS8602;
      CS8604;
      CS8618;
      CS8622;

      CS0618   <!-- Obsolete member used -->
    </NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazilla" Version="2.4.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Blazored.SessionStorage" Version="2.4.0" />
    <PackageReference Include="Blazorise" Version="1.6.1" />
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="FastReport.OpenSource" Version="2024.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Radzen.Blazor" Version="11.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="Telerik.Drawing.Skia" Version="19.3.25.1119" />
    <PackageReference Include="Telerik.Reporting" Version="19.3.25.1119" />
    <PackageReference Include="Telerik.Reporting.OpenXmlRendering" Version="19.3.25.1119" />
    <PackageReference Include="Telerik.Reporting.Services.AspNetCore" Version="19.3.25.1119" />
    <PackageReference Include="Telerik.UI.for.Blazor" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRApiLibrary\HRApiLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\u1C2PIS\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Home\Marketing.cshtml" />
  </ItemGroup>

</Project>
