namespace HRApiLibrary.Models._10_Pis.OPis;

public class OempmasModel
{
    public string? EmpNumber                { get; set; }
    public string? EmpLastName              { get; set; }
    public string? EmpFirstName             { get; set; }
    public string? EmpMiddleName            { get; set; }
    public string? Suffix                   { get; set; }
    public string? EmpAlias                 { get; set; }
    public string? Client                   { get; set; }
    public string? ClientCode               { get; set; }
    public string? BasicRate                { get; set; }
    public string? PayType                  { get; set; }
    public string? Admin                    { get; set; }
    public string? CashBond                 { get; set; }
    public string? WorkDays                 { get; set; }
    public string? AllowRate                { get; set; }
    public string? AllowType                { get; set; }
    public string? AllowFix                 { get; set; }
    public string? Allow2Rate               { get; set; }
    public string? Allow2Type               { get; set; }
    public string? Allow2Fix                { get; set; }
    public string? Allow3Rate               { get; set; }
    public string? Allow3Type               { get; set; }
    public string? Allow3Fix                { get; set; }
    public string? Allow4Rate               { get; set; }
    public string? Allow4Type               { get; set; }
    public string? Allow4Fix                { get; set; }
    public string? MovementNumber           { get; set; }
    public string? MovementMode             { get; set; }
    public string? MovementDate             { get; set; }
    public string? MovementEnd              { get; set; }
    public string? DutyDate                 { get; set; }
    public string? Address1                 { get; set; }
    public string? Address2                 { get; set; }
    public string? Tel1                     { get; set; }
    public string? Tel2                     { get; set; }
    public string? BirthDate                { get; set; }
    public string? BirthPlace               { get; set; }
    public string? Sex                      { get; set; }
    public string? CivilStatus              { get; set; }
    public string? Citizenship              { get; set; }
    public string? Height                   { get; set; }
    public string? Weight                   { get; set; }
    public string? Tin                      { get; set; }
    public string? Sss                      { get; set; }
    public string? PagIbig                  { get; set; }
    public string? PhilHealth               { get; set; }
    public string? Religion                 { get; set; }
    public string? Hair                     { get; set; }
    public string? Eyes                     { get; set; }
    public string? Spouse                   { get; set; }
    public string? Occupation               { get; set; }
    public string? NumberOfChildren         { get; set; }
    public string? DateHired                { get; set; }
    public string? SeparationDate           { get; set; }
    public string? Position                 { get; set; }
    public string? EmploymentStatus         { get; set; }
    public string? StatusDate               { get; set; }
    public string? SecurityLicense          { get; set; }
    public string? LicenseExpiry            { get; set; }
    public string? TrainingAt               { get; set; }
    public string? TrainingDate             { get; set; }
    public string? Insurance                { get; set; }
    public string? PolicyNumber             { get; set; }
    public string? FaceValue                { get; set; }
    public string? Premium                  { get; set; }
    public string? InsuranceExpiry          { get; set; }
    public string? EmergencyContactName     { get; set; }
    public string? EmergencyContactTel      { get; set; }
    public string? EmergencyContactAddress  { get; set; }
    public string? BloodType                { get; set; }
    public string? Age                      { get; set; }
    public string? Remarks                  { get; set; }
    public string? BadgeNumber              { get; set; }
    public string? Bank                     { get; set; }
    public string? Email                    { get; set; }
    public string? Password                 { get; set; }
    public string? DriverLicense            { get; set; }
    public string? DriverLicenseExpiry      { get; set; }
    public string? IsTaxable                { get; set; }
    public string? IsConfidential           { get; set; }
    public string? IsWithSss                { get; set; }
    public string? IsWithGsis               { get; set; }
    public string? IsWithPhilHealth         { get; set; }
    public string? IsWithPagIbig            { get; set; }  
}

